version: "3.9"
services:
  nginx:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8085:${NGINX_PORT}"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=${NGINX_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
    networks: 
      - web
    links: 
      - frontend
  # whoami:
  #   image: "traefik/whoami"
  #   container_name: "simple-service"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
  #     - "traefik.http.routers.whoami.entrypoints=websecure"
  #     - "traefik.http.routers.whoami.tls.certresolver=myresolver"
  admin:
    volumes:
      - ./admin:/admin
      - /admin/node_modules
      - ./common:/common
    build:
      context: .
      dockerfile: ./admin/Dockerfile
      target: "${NODE_ENV}"
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}
    environment: 
      - ADMIN_PORT=${ADMIN_PORT}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - api

  frontend:
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - ./common:/common
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: "${NODE_ENV}"
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment: 
      - FRONTEND_PORT=${FRONTEND_PORT}
      - NODE_ENV=${NODE_ENV}
    networks:
      - web
    depends_on:
      - api
  api:
    volumes:
     - ./api:/api
     - /api/node_modules
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: "${NODE_ENV}"
    ports:
      - ${API_PORT}:${API_PORT}
    environment: 
      - API_PORT=${API_PORT}
      - NODE_ENV=${NODE_ENV}
    #command: sh -c "npm install && npm run start:dev"

    networks:
      - backend
      - web
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      #MYSQL_ROOT_HOST: '%'
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend
   
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  adminer:
    image: adminer:4.6.3-standalone
   
    networks:
      - backend
      - web
    depends_on:
      - db
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   restart: always
  #   environment:
  #     PMA_USER: ${DB_USER}
  #     PMA_PASSWORD: ${DB_PASSWORD}
  #     PMA_CONTROLUSER: ${PHP_MY_ADMIN_USER}
  #     PMA_CONTROLPASS: ${PHP_MY_ADMIN_PASSWORD}
  #   networks:
  #     - backend
  #   ports:
  #     - "8090:80"
networks:
  backend: 
  web:
volumes: 
  data: {}