[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$8cQs7eip$dd1JGfb0AtVY7OvnzD3g10"
  ]

[http.routers.api]
  rule = "Host(`monitor.st-cms.ru`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"